### ISSUE TITLE
pypi tarball does not contains weakrefmethod.py file

### ISSUE THREAD

**Issue by chkumar246** [twang817/weakrefmethod#3]
The pypi tarball of weakrefmethod does not contains weakrefmethod.py.
[chandankumar@dhcp201-127 tmp]$ wget https://pypi.python.org/packages/source/w/weakrefmethod/weakrefmethod-1.0.1.tar.gz#md5=22d0cf91ea44b6c79a199dd44c8b28f3
--2015-10-06 19:37:40--  https://pypi.python.org/packages/source/w/weakrefmethod/weakrefmethod-1.0.1.tar.gz
Resolving pypi.python.org (pypi.python.org)... 23.235.46.223
Connecting to pypi.python.org (pypi.python.org)|23.235.46.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2203 (2.2K) [application/octet-stream]
Saving to: ‘weakrefmethod-1.0.1.tar.gz’

weakrefmethod-1.0.1.tar.gz                           100%[=======================================================================================================================>]   2.15K  --.-KB/s   in 0s     

2015-10-06 19:37:41 (869 MB/s) - ‘weakrefmethod-1.0.1.tar.gz’ saved [2203/2203]

[chandankumar@dhcp201-127 tmp]$ tar -xvf weakrefmethod-1.0.1.tar.gz 
weakrefmethod-1.0.1/
weakrefmethod-1.0.1/weakrefmethod.py
weakrefmethod-1.0.1/DESCRIPTION.rst
weakrefmethod-1.0.1/README.rst
weakrefmethod-1.0.1/setup.py
weakrefmethod-1.0.1/PKG-INFO
weakrefmethod-1.0.1/setup.cfg
weakrefmethod-1.0.1/MANIFEST.in
weakrefmethod-1.0.1/weakrefmethod.egg-info/
weakrefmethod-1.0.1/weakrefmethod.egg-info/dependency_links.txt
weakrefmethod-1.0.1/weakrefmethod.egg-info/SOURCES.txt
weakrefmethod-1.0.1/weakrefmethod.egg-info/PKG-INFO
weakrefmethod-1.0.1/weakrefmethod.egg-info/top_level.txt
and it is breaking on python setup.py test
[chandankumar@dhcp201-127 weakrefmethod-1.0.1]$ python setup.py test
running test
running egg_info
writing weakrefmethod.egg-info/PKG-INFO
writing top-level names to weakrefmethod.egg-info/top_level.txt
writing dependency_links to weakrefmethod.egg-info/dependency_links.txt
reading manifest file 'weakrefmethod.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'weakrefmethod.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 36, in <module>
    test_suite='test_weakmethod',
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 142, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 122, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 163, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = **import**('.'.join(parts_copy))
ImportError: No module named test_weakmethod
[chandankumar@dhcp201-127 weakrefmethod-1.0.1]$ 

Please fix it.

**Comment by twang817** [comment]
Should be fixed with latest commit
